// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"mykit/internal/auth/repository"
	"mykit/internal/auth/service"
)

// Injectors from container.go:

func CreateConcatService() *service.Service {
	server := repository.NewRepository()
	serviceService := service.NewService(server)
	return serviceService
}
